apiVersion: v2
name: hetzner-s3-operator
description: A Helm chart for the Hetzner S3 Operator
type: application
version: 0.1.1
appVersion: "0.1.1"
keywords:
  - s3
  - hetzner
  - operator
  - kubernetes
  - storage
home: https://github.com/kenchrcum/hetzner-s3-operator
sources:
  - https://github.com/kenchrcum/hetzner-s3-operator
maintainers:
  - name: kenchrcum
    url: https://github.com/kenchrcum
dependencies: []
